name 'base'
version '1.1.0'

depends 'apt'
depends 'build-essential'
depends 'chef-client'
depends 'cron'
depends 'hostsfile'
depends 'locale'
depends 'ntp'
depends 'postfix'
depends 'resolver'
depends 'sudo'
depends 'sysctl'
depends 'sysstat'
depends 'systemd'
depends 'ubuntu'
